### ISSUE TITLE
Rails 3.2.3 incompatibility

### ISSUE THREAD

**Issue by retorquere** [wingrunr21/gitolite#22] opened 2012-06-30 22:07 UTC
When I add gitolite to my Gemfile, and activerecord find request aborts with "stack level too deep". I don't even need to require the gem, simply having it in my gemfile triggers the bug.

**Comment by wingrunr21** [comment] 2012-07-01 10:09
First of all having a gem in your Gemfile auto requires it.  You need to specify <tt>:require => false</tt> to have it not required.

Second, can you give me a stack trace?  Also confirm this is different than Issue #19

**Comment by retorquere** [comment] 2012-07-01 11:35
It looks like #19, but including aspects before gitolite does not resolve the error.

$ rails console
Loading development environment (Rails 3.2.3)
1.9.3p194 :001 > User.find(1)
SystemStackError: stack level too deep
        from /home/hnse/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/irb/workspace.rb:80

**Comment by wingrunr21** [comment] 2012-07-01 23:26
Ok, I have created a test application and reproduced the problem.  The error is similar to #19.  It looks like the problem lies in the <tt>plexus</tt> gem requirement specifically instead of <tt>facets</tt>.  I will do some work on tracking down the exact problem.

**Comment by wingrunr21** [comment] 2012-08-03 16:05
<tt>plexus</tt> [Issue #2](https://github.com/chikamichi/plexus/issues/2) deals with the issue

**Comment by wingrunr21** [comment] 2012-08-03 17:00
Closing as #19 deals with this.

**Closed as completed by wingrunr21** 2012-08-03 17:00 UTC
Labels: bug, maintenance
